[workspace]
resolver = "2"
members = [
    "sidecar",
    "sidecar-common",
    "sidecar-ebpf",
    "xtask",
]
default-members = ["sidecar"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/bellistech/ebpf-sidecar"
